# File: .github/workflows/workflow.yml

on:
  pull_request:
    branches:
      - master

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - name: Setup Node ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: 'Build React client'
      run: |
        npm --prefix client install
        yarn --cwd "client" run build
      env:
        REACT_APP_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
        REACT_APP_REDIRECT_URI: ${{ secrets.LINKEDIN_OAUTH_REDIRECT_URL }}
    - name: 'Build Express app'
      run: |
        npm install
        npm run build --if-present
